config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root "articles#index"
  get '/comments/:id/edit', to: 'comments#edit', as: :edit_comment
  put '/comments/:id/edit', to: 'comments#update', as: :update_comment

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  has_many :comments, dependent: :destroy
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true
  validates_associated :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
  belongs_to :user

  validates :commenter, presence: true
  validates :body, presence: true
  validates_associated :user
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    VALID_STATUSES.each do |s|
      define_method("#{s}_count") do
        where(status: s).count
      end
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  
  has_many :articles
  has_many :comments


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :status, :user_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    # binding.pry
    @comment = Comment.find(params[:id])
    if @comment.update(update_comment_params)
      redirect_to article_path(@comment)
    else
      @comment.errors
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status, :user_id)
  end

  def update_comment_params
    params.permit(:commenter, :body, :status, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title , class: "bg-violet-600 text-dark rounded-md w-[100px] ml-auto mt-10 py-2"%>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body ,class: "bg-violet-600 text-dark rounded-md w-[100px] ml-auto mt-10 py-2"%><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
    <div>
    <%= form.number_field :user_id,type: :hidden, value: current_user.id %><br>
    <% article.errors.full_messages_for(:user_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>

<br>
  <div>
    <%= form.submit class: "bg-violet-600 text-white rounded-md w-[100px] ml-auto mt-10 py-2 btn btn-dark" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<p style="color: green"></p>
<div>
  <% @articles.each.with_index do |article, index| %>
<% unless article.archived? %>
<div class="card text-center">
  <div class="card-header bg-info">
  <h4>
  <%= article.title %>
  </h4>
  </div>
  <div class="card-body">
    <p class="card-text"> <%= article.body %></p>
    <%= link_to "show", article, class:"btn btn-dark" %>
  </div>
</div>
<br>
<% end %>
<% end %>




<% if user_signed_in?%>
<%= link_to "New Post", new_article_path,class:"btn btn-dark" %>
<%end%>
<br><br>
</div>

app/views/articles/new.html.erb
<h1>NEW POST</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div>
<p style="color: green"></p>
  <div class="bg-light clearfix">
  <div>
  <div class="card text-center">
    <div class="card-header bg-info">
      <h3 class="card-title"><%= @article.title %></h3>
    </div>
    <div class="card-body">
         <blockquote class="blockquote mb-0">
      <p class="card-text"><%= @article.body %>.</p>
      </blockquote>
    </div>
      <%if user_signed_in?%>
      <% if current_user.id == @article.user_id%>
        <div class="pull-left bg-light">  <ul>
          <%= link_to "Edit", edit_article_path(@article),class:"btn btn-dark" %>
          <%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  },class:"btn btn-dark" %>
          </ul></div>
          <% end%>
        </div>
</div>
</div>
</section>
<br><br>
<h2 class = "text-center">Comments</h2>
<p style="color: green"></p>

<div>
<%= render @article.comments %>
<br> <br>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
</div>
</div>
<%end%>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
<div class="card">
  <div class="card-header bg-info">
    <%= comment.commenter %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= comment.body %></h5>
    <p class="card-text"> </p>
    <% if user_signed_in?%>
    <% if current_user.id == comment.user_id %>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {turbo_method: :delete,turbo_confirm: "Are you sure?"},class:"btn btn-dark" %>
    <%= link_to "Edit", edit_comment_path([comment]),class:"btn btn-dark" %>
    <% end %>
    <% end %>
  </div>
</div>
<br>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.text_field :commenter,type: :hidden ,class: "p-2 border border-violet-500 rounded-md", size: "60x10", value: @article.title%>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body ,class: "p-2 border border-violet-500 rounded-md", size: "60x10"%>
  </p>
  <p>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' ,class: "p-2 border border-violet-500 rounded-md"%>
</p>
<p>
  <%= form.number_field :user_id,type: :hidden, value: current_user.id %><br>
<p>
  <p>
    <%= form.submit class: "bg-violet-600 text-white rounded-md w-[100px] ml-auto mt-10 py-2 btn btn-dark"%>
  </p>
<% end %>

app/views/comments/edit.html.erb
<div>
<br><br>
<h2>EDIT COMMENT</h2>
<br>
<%= form_with url: update_comment_path(@comment.id), method: :put do |form| %>
  <p>
<%= form.label :commenter, "commenter :"%>
  <%= form.text_field :commenter,class: "p-2 border border-violet-500 rounded-md", size: "60x10", value: @comment.commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body,class: "p-2 border border-violet-500 rounded-md", size: "60x10", value: @comment.body%>
  </p>
  <p>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</p>
<br>
  <p>
    <%= form.button class: "bg-violet-600 text-white rounded-md w-[100px] ml-auto mt-10 py-2 btn btn-dark"%>
  </p>
<% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item btn btn-dark" >
          <%= link_to "POST", articles_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item btn btn-dark">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link " %>
        </li>
      </ul>
      <ul>
        <li class="nav-item btn btn-dark">
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-link btn btn-danger" %>
        </li>
      </ul>
      <%else%>
      <li class="nav-item btn btn-dark">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
          <li class="nav-item btn btn-dark">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Post APP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <% if notice %>
    <div class="alert alert-success">
      <strong><%= notice %></strong> 
    </div>
    <% end%>

    <div class='container'>
        <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>













<%
=begin%>
 <!DOCTYPE html>
<html>
  <head>
    <title>Post</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  HEADER IN HERE...<br><br>
    <%= yield %>
  </body>
</html> 
<%
=end%>